## Adjacency Matrix and Lists

In [46]:
# V = {0, 1, 2, 3}
edges = [(0, 1), (0, 2), (1, 2), (3, 2)]

import numpy as np

# DIRECTED GRPAH - Adjacency matrix
A_d = np.zeros(shape = (len(edges), len(edges)))
for (i, j) in edges:
    A_d[i, j] = 1 # If i->j then change value to 1 in the matrix
print("Adjacency matrix for directed graph\n",A_d,'\n')


# UNDIRECTED GRPAH - Adjacency matrix
A_ud = np.zeros(shape = (len(edges), len(edges)))
for (i, j) in edges:
    A_ud[i, j] = 1
    A_ud[j, i] = 1
print("Adjacency matrix for un-directed graph\n",A_ud,'\n')


# COMPUTING NEIGHBOURS
def neighbours(AMat, i): # returns list of neighbours of i
    nbrs = []
    (rows, cols) = AMat.shape # numpy attribute
    for j in range(cols):
        if AMat[i, j] == 1:
            nbrs.append(j)
    return nbrs
print(f"Neighbours of vertex 0 are\n", neighbours(A_d, 0), '\n' )


# ADJECENCY LISTS
AList = {}
(rows, cols) = A_d.shape
for i in range(rows):
    AList[i] = []
for (i, j) in edges:
    AList[i].append(j)
print("Adjacency list for the undirected graph\n", AList,'\n')

Adjacency matrix for directed graph
 [[0. 1. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]] 

Adjacency matrix for un-directed graph
 [[0. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 0. 1. 0.]] 

Neighbours of vertex 0 are
 [1, 2] 

Adjacency list for the undirected graph
 {0: [1, 2], 1: [2], 2: [], 3: [2]} 



## Queue
- First in First Out data structure

In [15]:
class Queue:
    def __init__(self):
        self.queue = [] # underlying structure is a list
    def addq(self, v):
        self.queue.append(v) # append at the end
    def deleteq(self):
        v = None
        if not self.isempty():
            v = self.queue[0]
            self.queue = self.queue[1:] # slice the list, ignoring 0th element
        return v
    def isempty(self):
        return (self.queue == [])
    def __str__(self):
        return str(self.queue) # return the list (helps to print the queue)
    
queue = Queue()
for i in range(3):
    queue.addq(i)
    print("append: ", queue)
for i in range(3):
    queue.deleteq()
    print("delete: ",queue)

append:  [0]
append:  [0, 1]
append:  [0, 1, 2]
delete:  [1, 2]
delete:  [2]
delete:  []


## BFS: Adjacency Matrix

In [16]:
def BFS(AMat, v): # v is starting vertex, we want to check reachability of v
    (rows, cols) = AMat.shape
    visited = {} # key: vertex, value: true if it is reachable from v
    for i in range(rows):
        visited[i] = False # initializing each vertex to "not-visited"
    q = Queue()
    visited[v] = True # setting True for v
    q.addq(v) # v is to be explored first
    while(not q.isempty()): # while queue is not empty, keep exploring
        j = q.deleteq() # return the head of queue, now j is the index to be explored
        for k in neighbours(AMat, j): # visiting neighbours of j
            if (not visited[k]): # used to avoid adding visited index again in the queue
                visited[k] = True
                q.addq(k)
    return(visited) # all indexes which are set to True are reachable from vertex v

BFS(A_d, 0)

{0: True, 1: True, 2: True, 3: False}

## BFS: Adjacency List

In [17]:
def BFSList(AList, v): # AList is a dictionary (check above)
    visited = {}
    for i in AList.keys(): # list of indexes
        visited[i] = False
    q = Queue()
    visited[v] = True
    q.addq(v)
    while(not q.isempty()):
        j = q.deleteq()
        for k in AList[j]: 
            if (not visited[k]): 
                visited[k] = True
                q.addq(k)
    return(visited) 

BFSList(AList, 0)

{0: True, 1: True, 2: True, 3: False}

## Enhancing BFS to Record Paths

In [18]:
def BFSListPath(AList, v):
    (visited, parent) = ({},{})
    for i in AList.keys():
        visited[i] = False
        parent[i] = -1
    visited[v] = True # Parent of v is always -1
    q = Queue()
    q.addq(v) 
    while(not q.isempty()):
        j = q.deleteq()
        for k in AList[j]:
            if(not visited[k]):
                visited[k] = True
                parent[k] = j
                q.addq(k)
    return(visited, parent)

BFSListPath(AList, 0)

({0: True, 1: True, 2: True, 3: False}, {0: -1, 1: 0, 2: 0, 3: -1})

## Enhancing BFS to Record Distance

In [19]:
def BFSListPathLevel(AList, v):
    (level, parent) = ({},{})
    for i in AList.keys():
        level[i] = -1 # level is -1 => it is not visited
        parent[i] = -1
    level[v] = 0 # set level of v to be zero
    q = Queue()
    q.addq(v)
    while(not q.isempty()):
        j = q.deleteq()
        for k in AList[j]:
            if (level[k] == -1): # if not visited
                level[k] = level[j] + 1 # child level = parent level + 1
                parent[k] = j
                q.addq(k)
    return(level, parent)

BFSListPathLevel(AList, 0)

({0: 0, 1: 1, 2: 1, 3: -1}, {0: -1, 1: 0, 2: 0, 3: -1})

## DFS
- You need to create two functions
    - Initialization function, which intializes `visited` and `parent` according to size of input matrix/list
    - DFS function, which performs the DFS
- If you initialize `visited` and `parent` inside DFS then it would *re-initialize* values to `False` and `-1` on every recursive call

In [20]:
def DFSInit(AMat): # initialize visited and parent according to size of AMat
    (visited, parent) = ({}, {})
    (rows, cols) = AMat.shape
    for i in range(rows):
        visited[i] = False
        parent[i] = -1
    return (visited, parent)

def DFS(AMat, visited, parent, v):
    visited[v] = True
    for k in neighbours(AMat, v): # loop through the list of neighbours
        if (not visited[k]):
            parent[k] = v
            (visited, parent) = DFS(AMat,visited, parent, k) # suspend exploring v, explore k instead
    return (visited, parent) # returning these so that next call gets an updated visited, parent dictionary

(visited, parent) = DFSInit(A_d)
DFS(A_d, visited, parent, 0)

({0: True, 1: True, 2: True, 3: False}, {0: -1, 1: 0, 2: 1, 3: -1})

## DFS: Global Implementation
- We will keep `visited` and `parent` in global scope
- This makes it easier to handle these dictionaries

In [21]:
(visited, parent) = ({},{}) # intializing globally

def DFSInitGlobal(AMat):
    (rows, cols) = AMat.shape
    for i in range(rows):
        visited[i] = False
        parent[i] = -1
    return

def DFSGlobal(AMat, v):
    visited[v] = True
    for k in neighbours(AMat, v):
        if(not visited[k]):
            # visited[k] = True You do not need this! Think why...
            parent[k]  = v
            DFSGlobal(AMat, k)
    return # no need to return anything, both dicts are updated (as passed by reference)

DFSInitGlobal(A_d)
DFSGlobal(A_d, 0)
(visited, parent)

({0: True, 1: True, 2: True, 3: False}, {0: -1, 1: 0, 2: 1, 3: -1})

## DFS: Adjacency List

In [22]:
(visited, parent) = ({}, {})

def DFSInitListGlobal(AList):
    for i in AList.keys():
        visited[i] = False
        parent[i] = -1
    return

def DFSListGlobal(AList, v):
    visited[v] = True
    for k in AList[v]:
        if (not visited[k]):
            parent[k] = v
            DFSListGlobal(AList, k) # suspend exploring v, explore k now
    return

DFSInitListGlobal(AList)
DFSListGlobal(AList, 0)
(visited, parent)

({0: True, 1: True, 2: True, 3: False}, {0: -1, 1: 0, 2: 1, 3: -1})

## Identifying Connected Components

In [79]:
def Components(AList):
    component = {} # key = node, value = component number
    for i in AList.keys():
        component[i] = -1 # initially each vertex belongs to component no. -1
    (compid, seen) = (0, 0) # seen = total number of nodes visited, helps to stop loop
    while seen <= max(AList.keys()): # Equivalent to seen < len(AList.keys())
        startv = min([i for i in AList.keys() if component[i]==-1]) # start by taking the minimum vertex which is not visited        
        visited = BFSList(AList, startv) # this gives all reachable vertex from startv, which belong to one component
        for i in visited.keys():
            if visited[i]: # if we can reach i from startv => belongs to this component
                seen += 1
                component[i] = compid
        compid += 1 # increment to denote the next component
    return component


AList ={0: [2],1: [],2: [0, 3],3: [2],4:[]}
Components(AList)

{0: 0, 1: 1, 2: 0, 3: 0, 4: 2}

## DFS: Detecting Cycle

In [68]:
(visited, pre, post) = ({}, {}, {})

def DFSInitPrePost(AList):
    for i in AList.keys():
        visited[i] = False
        (pre[i], post[i]) = (-1, -1) # -ve pre => not visited, -ve post => still exploring, not finished

def DFSPrePost(AList, v, count=0): # count increments by one every time a new node is visited or finished exploring
    visited[v] = True
    pre[v] = count
    count += 1
    for k in AList[v]:
        if (not visited[k]):
            count = DFSPrePost(AList, k, count)
    post[v] = count
    count += 1
    return count # return count to keep track of the number accross recursive calls

AList = {0: [1, 2], 1: [0, 2], 2: [1, 2], 3: []}
DFSInitPrePost(AList)
DFSPrePost(AList, 0)
print("Visited: ", visited)
print("Pre: ", pre)
print("Post: ", post)

Visited:  {0: True, 1: True, 2: True, 3: False}
Pre:  {0: 0, 1: 1, 2: 2, 3: -1}
Post:  {0: 5, 1: 4, 2: 3, 3: -1}


## Topological Sort: Adjacency Matrix
- Compute indegrees by scanning columns of adjacency matrix
- List a vertex with indegree 0 and remove it from the DAG
- Update indegrees
- Repeat till all vertices are listed
- Time complxity: $O(n^2)$

In [69]:
def toposort(AMat):
    (rows, cols) = AMat.shape
    indegree = {} # keep track of indegrees of nodes
    toposortlist = [] # sorted sequence according to dependencies
    for c in range(cols): # computing indegrees of each node (runs n times)
        indegree[c] = 0
        for r in range(rows): # runs n times
            if AMat[r, c] == 1: # if r -> c, increment indegree of c
                indegree[c] += 1
    for i in range(rows): # runs n times (loop to enumerate vertices)
        j = min([k for k in range(cols) if indegree[k]==0]) # give the minimum node having no dependency (runs n times)
        toposortlist.append(j)
        indegree[j] -= 1 # make indegree -1  
        for k in range(cols): # updating indegrees of child nodes, runs n times
            if AMat[j, k] == 1:
                indegree[k] -= 1
    return toposortlist

toposort(A_d)

[0, 1, 3, 2]

## Topological Sort: Adjacency List
- Compute indegrees by scanning adjacency lists
- Maintain queue of vertices with indegree 0
- Enumerate head of queue, update indegrees, add indegree 0 to queue
- Repeat till queue is empty
- Time complxity: $O(m+n)$

In [72]:
def toposortlist(AList):
    (indegree, toposortlist) = ({}, [])
    for u in AList.keys(): # initializing indegrees of nodes to 0, runs n times
        indegree[u] = 0
    for u in AList.keys(): # runs n times
        for v in AList[u]: # in total runs m times (amortised analysis) -- Total number of out degrees = m
            indegree[v] += 1
    zerodegreeq = Queue()
    for u in AList.keys(): # run n times
        if indegree[u] == 0:
            zerodegreeq.addq(u) # add all nodes with no dependencies initially
    while (not zerodegreeq.isempty()): # runs n times (loop to enumerate vertices)
        j = zerodegreeq.deleteq() # deal with the first node in the queue with indegree=0
        toposortlist.append(j)
        indegree[j] -= 1 # make indegree -1
        for k in AList[j]: # in total runs m times (amortised analysis)
            indegree[k] -= 1  # update indegree of child node
            if indegree[k] == 0:
                zerodegreeq.addq(k) # add the child to queue
    return toposortlist

AList = {0: [1, 2], 1: [2], 2: [], 3: [2]} 
toposortlist(AList)

[0, 3, 1, 2]

## Longest Path: Adjacency List
- Compute indegrees by scanning adjacency lists
- Maintain queue of vertices with indegree 0
- Process head of queue: update indegrees, update queue, update longest paths
- Repeat till queue is empty
- Time complexity: $O(m+n)$

In [75]:
def longestpathlist(AList):
    (indegree, lpath) = ({}, {}) # lpath: key=node value= longest path length to the node
    for u in AList.keys():
        (indegree[u], lpath[u]) = (0, 0) # setting longest path lengths to 0 
    for u in AList.keys():
        for v in AList[u]: # Total number of out degrees = m, runs m times
            indegree[v] += 1 # finding indegrees of each node
    zerodegreeq = Queue()
    for u in AList.keys():
        if indegree[u] == 0:
            zerodegreeq.addq(u) # adding nodes with indegrees = 0 to the queue
    while(not zerodegreeq.isempty()): # runs n times (loop to enumerate vertices)
        j = zerodegreeq.deleteq() # deal with the node at the head of queue
        indegree[j] -= 1 # indegree becomes -1
        for k in AList[j]:
            indegree[k] -= 1 # update indegree
            lpath[k] = max(lpath[k], lpath[j]+1) # update lpath
            if indegree[k] == 0:
                zerodegreeq.addq(k)
    return lpath

AList = {0: [1, 2], 1: [2], 2: [], 3: [2]} 
longestpathlist(AList)

{0: 0, 1: 1, 2: 2, 3: 0}

## Extra Notes

In [ ]:
"""
You can start slicing i > len(lis)
    It does not give error
    You will get an []
"""
a = [2]
a[6:]

In [ ]:
"""
Dictionary is Passed-By-Reference
"""
d = {'a': 1, 'b': 3}
def add_c(dictionary):
    dictionary['c'] = 2
func(d)
d